{% set version = "3.3.0" %}
{% set blas_variant = "openblas" %}

package:
  name: opencv
  version: {{ version }}

source:
  fn: opencv-{{ version }}.tar.gz
  url: https://github.com/opencv/opencv/archive/{{ version }}.tar.gz
  sha256: 8bb312b9d9fd17336dc1f8b3ac82f021ca50e2034afc866098866176d985adc6

build:
  number: 201
  # Python2.7 support dropped: https://github.com/opencv/opencv/issues/8481
  skip: true  # [not linux]
  features:                    # [not win]
    - blas_{{ blas_variant }}  # [not win]

requirements:
  build:
    - python
    - toolchain
    - pkgconfig                    # [unix]
    # For sha256 comparisons of opencv_contrib
    - openssl 1.0.*                # [unix]
    # For downloading opencv_contrib
    - curl
    # For applying patches
    - git                          # [win]
    - cmake
    - numpy 1.8.*   # [not (win and (py35 or py36))]
    - numpy 1.9.*   # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - hdf5 1.8.18|1.8.18.*         # [unix]
    - eigen 3.2.*
    - jasper                       # [unix]
    - zlib 1.2.*

    # libjpegturbo
    # unlike systems where libjpegturbo is a drop-in replacement for libjpeg,
    # conda-forge libjpeg-turbo and jpeg packages fight against each other
    # (conda-forge jpeg is too new: https://libjpeg-turbo.org/About/Jpeg-9).
    # There is some clobbing going on there as well.
    # We link statically to libjpeg-turbo (see build.sh).
    - libjpeg-turbo 1.5*

    - libtiff 4.0.*
    - libwebp 0.5.*
    - harfbuzz 1.3.4               # [unix]
    - libpng >=1.6.28,<1.7
    - openblas 0.2.19|0.2.19.*     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]
    - ffmpeg >=3.3.3               # [not win]
    - qt 5.6.*                     # [not osx]

  run:
    - python
    - numpy >=1.8   # [not (win and (py35 or py36))]
    - numpy >=1.9   # [win and py35]
    - numpy >=1.11  # [win and py36]
    - hdf5 1.8.18|1.8.18.*         # [unix]
    - jasper                       # [unix]
    - zlib 1.2.*
    - libwebp 0.5.*
    - harfbuzz 1.3.4               # [unix]
    - libtiff 4.0.*
    - libpng >=1.6.28,<1.7
    - openblas 0.2.19|0.2.19.*     # [not win]
    - blas 1.1 {{ blas_variant }}  # [not win]
    - ffmpeg >=3.3.3               # [not win]
    - qt 5.6.*                     # [not osx]

test:
    imports:
      - cv2
      - cv2.xfeatures2d

    commands:
        # Verify dynamic libraries on all systems
        {% set opencv_libs = [
            "aruco",
            "bgsegm",
            "calib3d",
            "ccalib",
            "core",
            "datasets",
            "dnn",
            "dpm",
            "face",
            "features2d",
            "flann",
            "fuzzy",
            "highgui",
            "imgcodecs",
            "imgproc",
            "line_descriptor",
            "ml",
            "objdetect",
            "optflow",
            "phase_unwrapping",
            "photo",
            "plot",
            "reg",
            "rgbd",
            "saliency",
            "shape",
            "stereo",
            "stitching",
            "structured_light",
            "superres",
            "surface_matching",
            "text",
            "tracking",
            "video",
            "videoio",
            "videostab",
            "xfeatures2d",
            "ximgproc",
            "xobjdetect",
            "xphoto"
        ] %}
        {% for each_opencv_lib in opencv_libs %}
        - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}${SHLIB_EXT}                  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\opencv_{{ each_opencv_lib }}330.dll exit 1  # [win]
        {% endfor %}
        - test -f $PREFIX/lib/libopencv_bioinspired${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libopencv_hdf${SHLIB_EXT}          # [unix]
        - test -f $PREFIX/lib/libopencv_freetype${SHLIB_EXT}     # [unix]

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.

extra:
  upstream-recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
    - zym1010
    - hajapy
  recipe-maintainers:
    - sdvillal